### PR TITLE
activate tests for rigetti in pytket-braket

### PR DESCRIPTION
**Pull request by cqc-melf**

### CODE REVIEW

**Comment by cqc-melf** [comment]
The failure of the tests is expected. Not sure if this reactivation should wait until it works again or should be merged now. @cqc-alec

**Comment by cqc-alec** [comment]
Let's wait till the device is back online before merging this PR.
As a longer-term solution, we should perhaps be querying the available devices at the start of these tests and simply skipping them if the device is offline.

**Comment by cqc-alec** [comment]
The device is still offline. Perhaps we should switch to using the `Aspen-11` device instead of the `Aspen-M-1` in the tests.

**Review by cqc-alec — CHANGES_REQUESTED** [review]
Please could you try swapping `Aspen-11` for `Aspen-M-1` in these three tests?

**Comment by cqc-melf** [comment]
> Please could you try swapping `Aspen-11` for `Aspen-M-1` in these three tests?

Yes will do that.

**Comment by cqc-melf** [comment]
Looks like that is not helping?

**Comment by cqc-alec** [comment]
> Looks like that is not helping?

Looks like the device ARN is `arn:aws:braket:::device/qpu/rigetti/Aspen-11`. Try setting `region=""` when constructing the backend?

**Comment by cqc-melf** [comment]
I have taken a detailed look on the error message, but I am not sure what the problem is in the different cases. Any idea?

**Comment by cqc-alec** [comment]
> I have taken a detailed look on the error message, but I am not sure what the problem is in the different cases. Any idea?

Not sure, this may require debugging locally. Feel free to reassign this to me and I will take a look.

**Comment by cqc-melf** [comment]
I don't have the credentials to run that locally. I think we had no task for this yet, will create one now.

**Comment by cqc-melf** [comment]
I will close this PR and reopen it on the new repo, any objections @cqc-alec ?

**Comment by cqc-alec** [comment]
> I will close this PR and reopen it on the new repo, any objections @cqc-alec ?

No objections.

**Pull request closed without merging**
