### PR TITLE
Update to qsharp 0.20.

### LINKED ISSUE #234: [pytket-qsharp] Update to qsharp 0.20.

### PR DESCRIPTION
**Pull request by cqc-alec**
Closes #234 .

### CODE REVIEW

**Comment by cqc-melf** [comment]
Have you checked if this closes https://github.com/CQCL/pytket-extensions/issues/180, too?

**Comment by cqc-alec** [comment]
> Have you checked if this closes #180, too?

No, but I plan to check that after the update.

**Comment by cqc-melf** [comment]
I think this PR is not executing the tests for Windows on python 3.7, have you executed them somewhere else?

**Comment by cqc-alec** [comment]
> I think this PR is not executing the tests for Windows on python 3.7, have you executed them somewhere else?

I have run all the tests locally including the remote tests requiring azure credentials.
Unfortunately we can't run the Windows tests at the moment because of #180 .

**Review by cqc-melf — APPROVED** [review]

**Pull request merged**
