### PR TITLE
Remove/iqm braket

### PR DESCRIPTION
**Pull request by cqc-melf**
moved to new repo

### CODE REVIEW

**Review by cqc-alec — APPROVED** [review]

**Comment by cqc-alec** [comment]
Perhaps wait for successful releases from new repo before merging?

**Comment by cqc-alec** [comment]
> Perhaps wait for successful releases from new repos before merging?

On second thoughts, these are the ones that were failing because of remote issues, right? So scratch that.

**Comment by cqc-melf** [comment]
I have made RC releases from the new repos for which I had to disable the remote tests, so it would be possible to to a real release if you want?

**Comment by cqc-melf** [comment]
See https://pypi.org/project/pytket-braket/#history and https://pypi.org/project/pytket-iqm/#history
For pytket iqm it might be interesting to do a real release even with the not working tests, because the version containing pytket .10 has not been released yet. But I still think it would be better to solve the issues before doing that.

**Comment by cqc-alec** [comment]
Yeah, I don't think there's an urgent need to release either yet.

**Pull request merged**
